name: resep_nusantara
description: Aplikasi Resep Nusantara - Submission Kelas Flutter Pemula Dicoding
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  rating_bar: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: Tajawal-Bold
      fonts:
        - asset: fonts/Tajawal/Tajawal-Bold.ttf
    - family: Tajawal-Regular
      fonts:
        - asset: fonts/Tajawal/Tajawal-Regular.ttf

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
